site_name: uproot
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
    - scheme: slate
      toggle:
        icon: material/brightness-4

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - codehilite

copyright: |
  The documentation and all code examples are licensed under the <a href="https://opensource.org/licenses/0BSD">0BSD License</a> unless stated otherwise.

nav:
  - Home: index.md
  - Examples: examples.md
